# Generated by Django 4.0.7 on 2022-09-03 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qos',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('L', 'Living Item')], default=('F', 'Food'), max_length=1, verbose_name='Category'),
        ),
    ]
