# Generated by Django 4.0.7 on 2022-09-03 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_qos_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qos',
            name='category',
        ),
    ]
